### ISSUE TITLE
DEFAULTSORT could be improved

### ISSUE THREAD

**Issue by papuass** [kosovojs/wikibooster#2]
booster offers me to add DEFUALTSORT to this page:

**{{JÄRJESTA:Vinter, Ülo}}**
[[Kategooria: Eesti heliloojad|_Vinter, Ülo_]]
[[Kategooria: Sündinud 1924|_Vinter, Ülo_]]
[[Kategooria: Surnud 2000|_Vinter, Ülo_]]

But it could be improved as sorting parameter in categories is redundant now and these could be deleted.

**Comment by kosovojs** [comment]
Implemented. See [example](https://et.wikipedia.org/w/index.php?title=Katsushika_Hokusai&type=revision&diff=5452763&oldid=4805740).

Catsort parameters will be removed only if equal to DEFAULTSORT, that is being added.
