### ISSUE TITLE
Link to open for editing in WIkipedia

### ISSUE THREAD

**Issue by papuass** [kosovojs/wikibooster#3]
In rare cases suggested fix is not correct, but manual edit is neccesary instead.

There should be link to open article for editing in Wikipedia wikicode editor and possibly scroll to displayed excerpt. 

Clicking on title opens page in read mode.

**Comment by kosovojs** [comment]
Added both editing option in the tool itself (should be working in most cases) and link to edit mode.

About "possibly scroll to displayed excerpt" - won't gonna happen, probably.
