### ISSUE TITLE
Blank page reloaded in unclear scenario

### ISSUE THREAD

**Issue by papuass** [kosovojs/wikibooster#4]
Sometimes I get this error.

Scenario is something like:
1. play the game, accepting some edits
2. click on some other item in list (skipping ~20 items)
3. booster UI disappears from browser, blank page

Just happened in DEFAULTSORT game.

Stack trace
> Uncaught (in promise) TypeError: Cannot read property 'substr' of undefined
>     at t.diff (WikEdDiff.js:964)

**Comment by kosovojs** [comment]
Should be fixed. Thanks!
